id = "anthracite-org/magnum-v4-72b"
name = "Magnum v4 72B"
release_date = "2024-10-22"
last_updated = "2025-12-08"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = 3e-6
output = 5e-6

[limit]
context = 16384
output = 2048

[modalities]
input = [ "text",]
output = [ "text",]
