id = "nvidia/nemotron-nano-12b-v2-vl"
name = "NVIDIA: Nemotron Nano 12B 2 VL"
release_date = "2025-10-28"
last_updated = "2025-12-08"
attachment = true
reasoning = true
temperature = true
tool_call = false
open_weights = false

[cost]
input = 2e-7
output = 6e-7

[limit]
context = 131072
output = 4096

[modalities]
input = [ "image", "text", "video",]
output = [ "text",]
