id = "meta-llama/llama-3.1-405b-instruct"
name = "Meta: Llama 3.1 405B Instruct"
release_date = "2024-07-23"
last_updated = "2025-12-08"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false
knowledge = "2023-12"

[cost]
input = 3.5e-6
output = 3.5e-6

[limit]
context = 130815
output = 4096

[modalities]
input = [ "text",]
output = [ "text",]
