id = "meta-llama/llama-4-maverick"
name = "Meta: Llama 4 Maverick"
release_date = "2025-04-05"
last_updated = "2025-11-02"
attachment = true
reasoning = false
temperature = true
tool_call = true
open_weights = false

[cost]
input = 1.5e-7
output = 6e-7

[limit]
context = 1048576
output = 16384

[modalities]
input = [ "text", "image",]
output = [ "text",]
