id = "essentialai/rnj-1-instruct"
name = "EssentialAI: Rnj 1 Instruct"
release_date = "2025-12-07"
last_updated = "2025-12-08"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = 1.5e-7
output = 1.5e-7

[limit]
context = 32768
output = 4096

[modalities]
input = [ "text",]
output = [ "text",]
