id = "google/gemini-2.5-flash-preview-09-2025"
name = "Google: Gemini 2.5 Flash Preview 09-2025"
release_date = "2025-09-25"
last_updated = "2025-11-02"
attachment = true
reasoning = true
temperature = true
tool_call = true
open_weights = false
knowledge = "2025-01"

[cost]
input = 3e-7
output = 2.5e-6
cache_read = 7.5e-8
cache_write = 3.833e-7

[limit]
context = 1048576
output = 65536

[modalities]
input = [ "image", "text", "audio",]
output = [ "text",]
