id = "qwen/qwen3-vl-235b-a22b-thinking"
name = "Qwen: Qwen3 VL 235B A22B Thinking"
release_date = "2025-09-24"
last_updated = "2025-12-08"
attachment = true
reasoning = true
temperature = true
tool_call = true
open_weights = false

[cost]
input = 3e-7
output = 1.2e-6

[limit]
context = 262144
output = 262144

[modalities]
input = [ "text", "image",]
output = [ "text",]
