id = "qwen/qwen-plus-2025-07-28:thinking"
name = "Qwen: Qwen Plus 0728 (thinking)"
release_date = "2025-09-08"
last_updated = "2025-11-02"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false

[cost]
input = 4e-7
output = 4e-6

[limit]
context = 1000000
output = 32768

[modalities]
input = [ "text",]
output = [ "text",]
