id = "qwen/qwen3-next-80b-a3b-instruct"
name = "Qwen: Qwen3 Next 80B A3B Instruct"
release_date = "2025-09-11"
last_updated = "2025-11-02"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false
knowledge = "2025-04"

[cost]
input = 1e-7
output = 8e-7

[limit]
context = 262144
output = 262144

[modalities]
input = [ "text",]
output = [ "text",]
