id = "qwen/qwen3-vl-32b-instruct"
name = "Qwen: Qwen3 VL 32B Instruct"
release_date = "2025-10-23"
last_updated = "2025-11-02"
attachment = true
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = 3.5e-7
output = 1.1e-6

[limit]
context = 262144
output = 262144

[modalities]
input = [ "text", "image",]
output = [ "text",]
