id = "qwen/qwen3-max"
name = "Qwen: Qwen3 Max"
release_date = "2025-09-23"
last_updated = "2025-11-02"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false

[cost]
input = 1.2e-6
output = 6e-6
cache_read = 2.4e-7

[limit]
context = 256000
output = 32768

[modalities]
input = [ "text",]
output = [ "text",]
