id = "qwen/qwen2.5-vl-32b-instruct:free"
name = "Qwen: Qwen2.5 VL 32B Instruct (free)"
release_date = "2025-03-24"
last_updated = "2025-11-02"
attachment = true
reasoning = false
temperature = true
tool_call = false
open_weights = true
knowledge = "2025-03"

[cost]
input = 0
output = 0

[limit]
context = 16384
output = 4096

[modalities]
input = [ "text", "image",]
output = [ "text",]
