id = "qwen/qwen3-235b-a22b-thinking-2507"
name = "Qwen: Qwen3 235B A22B Thinking 2507"
release_date = "2025-07-25"
last_updated = "2025-12-08"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false
knowledge = "2025-04"

[cost]
input = 1.1e-7
output = 6e-7

[limit]
context = 262144
output = 262144

[modalities]
input = [ "text",]
output = [ "text",]
