id = "moonshotai/kimi-k2-0905:exacto"
name = "MoonshotAI: Kimi K2 0905 (exacto)"
release_date = "2025-09-04"
last_updated = "2025-12-08"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false
knowledge = "2024-10"

[cost]
input = 6e-7
output = 2.5e-6

[limit]
context = 262144
output = 4096

[modalities]
input = [ "text",]
output = [ "text",]
