id = "moonshotai/kimi-k2"
name = "MoonshotAI: Kimi K2 0711"
release_date = "2025-07-11"
last_updated = "2025-12-08"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false
knowledge = "2024-10"

[cost]
input = 4.56e-7
output = 1.84e-6

[limit]
context = 131072
output = 131072

[modalities]
input = [ "text",]
output = [ "text",]
