id = "moonshotai/kimi-k2-0905"
name = "MoonshotAI: Kimi K2 0905"
release_date = "2025-09-04"
last_updated = "2025-11-02"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false
knowledge = "2024-10"

[cost]
input = 3.9e-7
output = 1.9e-6

[limit]
context = 262144
output = 262144

[modalities]
input = [ "text",]
output = [ "text",]
