id = "shisa-ai/shisa-v2-llama3.3-70b:free"
name = "Shisa AI: Shisa V2 Llama 3.3 70B  (free)"
release_date = "2025-04-15"
last_updated = "2025-11-02"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = true

[cost]
input = 0
output = 0

[limit]
context = 32768
output = 4096

[modalities]
input = [ "text",]
output = [ "text",]
