id = "morph/morph-v3-large"
name = "Morph: Morph V3 Large"
release_date = "2025-07-07"
last_updated = "2025-11-02"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = 9e-7
output = 1.9e-6

[limit]
context = 262144
output = 131072

[modalities]
input = [ "text",]
output = [ "text",]
