id = "mistralai/devstral-small"
name = "Mistral: Devstral Small 1.1"
release_date = "2025-07-10"
last_updated = "2025-11-02"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false

[cost]
input = 7e-8
output = 2.8e-7

[limit]
context = 128000
output = 4096

[modalities]
input = [ "text",]
output = [ "text",]
