id = "mistralai/magistral-medium-2506:thinking"
name = "Mistral: Magistral Medium 2506 (thinking)"
release_date = "2025-06-07"
last_updated = "2025-11-02"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false

[cost]
input = 2e-6
output = 5e-6

[limit]
context = 40960
output = 40000

[modalities]
input = [ "text",]
output = [ "text",]
