id = "mistralai/pixtral-12b"
name = "Mistral: Pixtral 12B"
release_date = "2024-09-09"
last_updated = "2025-11-02"
attachment = true
reasoning = false
temperature = true
tool_call = true
open_weights = false

[cost]
input = 1e-7
output = 1e-7

[limit]
context = 32768
output = 4096

[modalities]
input = [ "text", "image",]
output = [ "text",]
