id = "z-ai/glm-4.5v"
name = "Z.AI: GLM 4.5V"
release_date = "2025-08-11"
last_updated = "2025-12-08"
attachment = true
reasoning = true
temperature = true
tool_call = true
open_weights = false
knowledge = "2025-04"

[cost]
input = 4.8e-7
output = 1.44e-6
cache_read = 8.8e-8

[limit]
context = 65536
output = 16384

[modalities]
input = [ "text", "image",]
output = [ "text",]
