id = "minimax/minimax-01"
name = "MiniMax: MiniMax-01"
release_date = "2025-01-14"
last_updated = "2025-11-02"
attachment = true
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = 2e-7
output = 1.1e-6

[limit]
context = 1000192
output = 1000192

[modalities]
input = [ "text", "image",]
output = [ "text",]
