id = "baidu/ernie-4.5-vl-28b-a3b"
name = "Baidu: ERNIE 4.5 VL 28B A3B"
release_date = "2025-08-12"
last_updated = "2025-12-08"
attachment = true
reasoning = true
temperature = true
tool_call = true
open_weights = false

[cost]
input = 1.12e-7
output = 4.48e-7

[limit]
context = 30000
output = 8000

[modalities]
input = [ "text", "image",]
output = [ "text",]
