id = "allenai/olmo-2-0325-32b-instruct"
name = "AllenAI: Olmo 2 32B Instruct"
release_date = "2025-03-14"
last_updated = "2025-12-08"
attachment = false
reasoning = false
temperature = false
tool_call = false
open_weights = false

[cost]
input = 5e-8
output = 2e-7

[limit]
context = 128000
output = 4096

[modalities]
input = [ "text",]
output = [ "text",]
