id = "thedrummer/anubis-70b-v1.1"
name = "TheDrummer: Anubis 70B V1.1"
release_date = "2025-06-29"
last_updated = "2025-11-02"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = 6.5e-7
output = 1e-6

[limit]
context = 131072
output = 131072

[modalities]
input = [ "text",]
output = [ "text",]
