id = "deepseek/deepseek-v3.1-terminus"
name = "DeepSeek: DeepSeek V3.1 Terminus"
release_date = "2025-09-22"
last_updated = "2025-12-08"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false
knowledge = "2025-07"

[cost]
input = 2.1e-7
output = 7.9e-7
cache_read = 1.68e-7

[limit]
context = 163840
output = 4096

[modalities]
input = [ "text",]
output = [ "text",]
