id = "openai/gpt-5-mini"
name = "OpenAI: GPT-5 Mini"
release_date = "2025-08-07"
last_updated = "2025-12-08"
attachment = true
reasoning = true
temperature = false
tool_call = true
open_weights = false
knowledge = "2024-10-01"

[cost]
input = 2.5e-7
output = 2e-6
cache_read = 2.5e-8

[limit]
context = 400000
output = 128000

[modalities]
input = [ "text", "image",]
output = [ "text",]
