id = "openai/gpt-oss-safeguard-20b"
name = "OpenAI: gpt-oss-safeguard-20b"
release_date = "2025-10-29"
last_updated = "2025-12-08"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false

[cost]
input = 7.5e-8
output = 3e-7
cache_read = 3.7e-8

[limit]
context = 131072
output = 65536

[modalities]
input = [ "text",]
output = [ "text",]
