id = "openai/gpt-3.5-turbo"
name = "OpenAI: GPT-3.5 Turbo"
release_date = "2023-05-28"
last_updated = "2025-12-08"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false

[cost]
input = 5e-7
output = 1.5e-6

[limit]
context = 16385
output = 4096

[modalities]
input = [ "text",]
output = [ "text",]
