id = "openai/gpt-5-chat"
name = "OpenAI: GPT-5 Chat"
release_date = "2025-08-07"
last_updated = "2025-12-08"
attachment = true
reasoning = false
temperature = false
tool_call = false
open_weights = false
knowledge = "2024-09-30"

[cost]
input = 1.25e-6
output = 1e-5
cache_read = 1.25e-7

[limit]
context = 128000
output = 16384

[modalities]
input = [ "image", "text",]
output = [ "text",]
