id = "openai/o1-pro"
name = "OpenAI: o1-pro"
release_date = "2025-03-19"
last_updated = "2025-11-02"
attachment = true
reasoning = true
temperature = false
tool_call = false
open_weights = false

[cost]
input = 0.00015
output = 0.0006

[limit]
context = 200000
output = 100000

[modalities]
input = [ "text", "image",]
output = [ "text",]
